# Generated by Django 2.2.7 on 2019-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=13, help_text='Longitude Location', max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=13, help_text='Latitude Location', max_digits=15)),
                ('unique_squirrel_id', models.CharField(help_text='Squirrel ID', max_length=100)),
                ('hectare', models.CharField(help_text='Hectare', max_length=100)),
                ('shift', models.CharField(choices=[('pm', 'PM'), ('am', 'PM')], help_text='Squirrels Shift', max_length=2)),
                ('date', models.DateField(help_text='Date of sighting')),
                ('hectare_squirrel_number', models.IntegerField(help_text='Number of the sighting session')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=10)),
                ('primary_fur_color', models.CharField(choices=[('cinnamon', 'Cinnamon'), ('white', 'White'), ('balck', 'Black')], help_text='Primary fur color', max_length=20)),
                ('location', models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane')], help_text='Location of First Sight of the squirrel', max_length=20)),
                ('specific_location', models.CharField(help_text='Specific Location', max_length=100)),
            ],
        ),
    ]
