# Generated by Django 2.2.7 on 2019-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], default='', help_text='Age of squirrel', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default='', help_text='Date of sighting'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare',
            field=models.CharField(default='', help_text='Hectare', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare_squirrel_number',
            field=models.IntegerField(default='', help_text='Number of the sighting session'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(decimal_places=13, default='', help_text='Latitude Location', max_digits=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane')], default='', help_text='Location of First Sight of the squirrel', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(decimal_places=13, default='', help_text='Longitude Location', max_digits=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='', help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('cinnamon', 'Cinnamon'), ('white', 'White'), ('balck', 'Black')], default='', help_text='Primary fur color', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('pm', 'PM'), ('am', 'AM'), ('', '')], default='', help_text='Squirrels Shift', max_length=2),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default='', help_text='Specific Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(default='', help_text='Squirrel ID', max_length=100),
        ),
    ]
