# Generated by Django 2.2.7 on 2019-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20191202_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen approaching human'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen chasing another squirrel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen climbing a tree or other environmental landmark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen eating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen foraging for food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was indifferent to human presence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was heard kukking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was heard moaning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='', help_text='Other Activities', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was heard quaaing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen running.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen running from humans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen flagging its tail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default='FALSE', help_text='Squirrel was seen twitching its tail'),
            preserve_default=False,
        ),
    ]
