# Generated by Django 2.2.7 on 2019-12-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20191209_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, help_text='Date of sighting'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare',
            field=models.CharField(blank=True, help_text='Hectare', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare_squirrel_number',
            field=models.IntegerField(blank=True, help_text='Number of the sighting session'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, help_text='Latitude Location', max_digits=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane')], help_text='Location of First Sight of the squirrel', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, help_text='Longitude Location', max_digits=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('cinnamon', 'Cinnamon'), ('white', 'White'), ('balck', 'Black')], help_text='Primary fur color', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(blank=True, help_text='Squirrel ID', max_length=100),
        ),
    ]
