# Generated by Django 2.2.7 on 2019-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20191209_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(decimal_places=13, default='0', help_text='Latitude Location', max_digits=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(decimal_places=13, default='0', help_text='Longitude Location', max_digits=15),
        ),
    ]
