# Generated by Django 2.2.7 on 2019-12-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20191209_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default='2000-01-01', help_text='Date of sighting'),
        ),
    ]
