# Generated by Django 2.2.7 on 2019-12-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20191209_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='hectare_squirrel_number',
            field=models.IntegerField(default='0', help_text='Number of the sighting session'),
        ),
    ]
